### ISSUE TITLE
Add CONDUCT.md with code of conduct

### ISSUE THREAD

**Issue by jameslamb** [jameslamb/doppel-cli#117]
This project should have a file `CONDUCT.md` with a code of conduct. [this one](https://github.com/UptakeOpenSource/pkgnet/blob/master/CONDUCT.md) is pretty good but I'm open to other suggestions.

**Comment by RikTheunis** [comment]
@jameslamb the link to the code of conduct is broken. I see the project you were referring to uses the [*Contributor Covenant Code of Conduct*](https://www.contributor-covenant.org/version/1/4/code-of-conduct). Do you still want that one?

**Comment by jameslamb** [comment]
ah apologies, yes that one is good! Thank you!

**Comment by RikTheunis** [comment]
I will add that one! I just need an email address to insert here:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by contacting the project team at [INSERT EMAIL ADDRESS]. All complaints will be reviewed and investigated and will result in a response that is deemed necessary and appropriate to the circumstances. The project team is obligated to maintain confidentiality with regard to the reporter of an incident. Further details of specific enforcement policies may be posted separately.

**Comment by jameslamb** [comment]
awesome, thanks. `jaylamb20@gmail.com` please
