### ISSUE TITLE
100% coverage of analyze.py

### ISSUE THREAD

**Issue by jameslamb** [jameslamb/doppel-cli#135]
This is dependent on #56 . Closing this issue means writing tests AND setting a coverage threshold for the `analyze.py` tests in `.ci/test.sh`.

**Comment by jameslamb** [comment]
this was incorrectly closed by a bad commit message on #137

**Comment by jameslamb** [comment]
To test:

```
./.ci/run_analyze_py_coverage.sh 0
cd .ci/analyze_py_tests
coverage html
open htmlcov/index.html
```

**Comment by jameslamb** [comment]
@Physsix27 I saw your comment on #143 . Let's chat here.

Yes I could still use some help with testing `analyze.py`! See #143 as a reference of what parts of the repo you might need to touch, and the details here in this issue for how to check which lines remain uncovered.

If you have any questions about how to get started on the issue after reading the details there, let me know. I would love some help!

That is the final issue left [to complete the 0.3.0 milestone](https://github.com/jameslamb/doppel-cli/milestone/2) so it would be awesome to get it done 😀

**Comment by Physsix27** [comment]
I would be more than happy to help, I will open a PR once is done, please assigned to me. 😀

**Comment by jameslamb** [comment]
Done, thank you!

**Comment by Physsix27** [comment]
![image](https://user-images.githubusercontent.com/36493537/66439548-036dc000-e9fe-11e9-82a5-51952f96e2df.png)
So is this how the `test coverage` is currently looking like for `analyze.py`?

**Comment by Physsix27** [comment]
Hey @jameslamb, I just want it to double-check, the `analyze.py` that you are referring to is -> `doppel/bin/analyze.py`?
I will be creating a `test_analyze.py` python file inside of `tests/test_analyze.py` or I should be adding to -> `integration_tests/python_tests/test_analyze.py`

**Comment by jameslamb** [comment]
@Physsix27 Sorry for the delayed response! Let's keep all discussion here.

So if you run the steps from the comments above on the current version on `master` (modified to include re-installing) you will see a result like this in your console:

```
test_analyze_py.py .                                                     [100%]

---------- coverage: platform darwin, python 3.6.7-final-0 -----------
Name                Stmts   Miss  Cover
---------------------------------------
doppel_analyze.py     118      9    92%


=========================== 1 passed in 0.06 seconds ===========================
Name                Stmts   Miss  Cover   Missing
-------------------------------------------------
doppel_analyze.py     118      9    92%   74, 190, 203-208, 252, 272-273
```

I got that by running the following form the root of the repo

```
pip install .
./.ci/run_analyze_py_coverage.sh 0
```

That shows that the current test coverage is 92%.

After running those, you can view the HTML report that shows individual covered / uncovered lines with

```
cd .ci/analyze_py_tests
coverage html
open htmlcov/index.html
```

To try to address the remaining 8%, you should look at which files I touched in #143 . Namely, I had to add tests in `integration_tests/python_tests/test_analyze.py` and I had to add some additional types of code to the test packages in `integration_tests/test_packages`.

I just found some lingering changes on my laptop that I forgot to push onto #143 , so I'm actually going to open up a PR right now that I think should make this really clear.

**Comment by jameslamb** [comment]
Ok see #149 . Note the files I had to touch:

* `integration_tests/python_tests/test_analyze.py` (add new tests)
* `integration_tests/test-packages/*` (you will have to touch some files in this directory or maybe add new ones to hit additional uncovered lines).

I've also attached the new coverage HTML file as of that PR here. GitHub doesn't allow you to upload `.html` files as attachments (it probably messes with their site), so change the extension of this file from `.txt` to `.html` and you should be able to view it in your browser

[coverage.txt](https://github.com/jameslamb/doppel-cli/files/3709789/coverage.txt)

Also, I realize now that there are two lines of this that you won't be able to test with unit tests:

![image](https://user-images.githubusercontent.com/7608904/66527685-da0e6c00-eab1-11e9-879a-ad6128c5cf01.png)

You can safely ignore those. So if you can provide a PR that tests the remaining 6 lines, we can close this issue!

**Comment by jameslamb** [comment]
I know this is a ton of information...if you have questions, don't hesitate to ask.

**Comment by Physsix27** [comment]
Alright, I am on the same page with you.

**Comment by Physsix27** [comment]
I am trying to run those commands but I don't get the same result and I get an error

**Comment by jameslamb** [comment]
@Physsix27 can you show me the error and any other relevant logs?

**Comment by Physsix27** [comment]
```./.ci/run_analyze_py_coverage.sh 0
cd .ci/analyze_py_tests
coverage html
open htmlcov/index.html```
This steps are not working to run the tests.
First thing, how are you running the tests? with `pytest`, `python3 -m unittest`? I don't know what you are using, you need something to run the tests so and collect the data to put it inside of `.coverage` so `coverage html` can work and print something out

**Comment by jameslamb** [comment]
@Physsix27 apologies for the delayed response, I've been traveling and trying to stay off email / open source during it. But I'm back now!

I think I made things more confusing by breaking up the commands into two blocks in [this comment](https://github.com/jameslamb/doppel-cli/issues/135#issuecomment-540246220). Sorry!

The full thing you need to run to re-install from source, run the tests, and look at the coverage report (from the repo root):

```
pip install .
./.ci/run_analyze_py_coverage.sh 0
cd .ci/analyze_py_tests
coverage html
open htmlcov/index.html
```

Let me know if you run into any issues with that.
