### ISSUE TITLE
[ci] move linting configuration into dotfiles

### ISSUE THREAD

**Issue by jameslamb** [jameslamb/doppel-cli#206]
Some of the configuration of linters in this project is stored in command-line arguments in scripts.

For example:

https://github.com/jameslamb/doppel-cli/blob/7da04669778cb42fae9711eed6f51281194645a9/.ci/lint-py.sh#L25-L29

This configuration should be moved to standard config files like `pyproject.toml` or `setup.cfg`:

1. so that IDEs like PyCharm will automatically use the correct settings
2. to avoid mistakes like the one I made in https://github.com/jameslamb/doppel-cli/pull/205#pullrequestreview-796063959

## Notes

For an example of such configuration files, see https://github.com/saturncloud/prefect-saturn/pull/27

**Comment by Talha119119** [comment]
> Some of the configuration of linters in this project is stored in command-line arguments in scripts.
> 
> For example:
> 
> https://github.com/jameslamb/doppel-cli/blob/7da04669778cb42fae9711eed6f51281194645a9/.ci/lint-py.sh#L25-L29
> 
> This configuration should be moved to standard config files like `pyproject.toml` or `setup.cfg`:
> 
> 1. so that IDEs like PyCharm will automatically use the correct settings
> 2. to avoid mistakes like the one I made in [use f-strings for string formatting (fixes #204) #205 (review)](https://github.com/jameslamb/doppel-cli/pull/205#pullrequestreview-796063959)
> 
> ## Notes
> For an example of such configuration files, see [saturncloud/prefect-saturn#27](https://github.com/saturncloud/prefect-saturn/pull/27)

gh pr checkout 42954
