### ISSUE TITLE
Add a Python 3.5 version floor

### ISSUE THREAD

**Issue by jameslamb** [jameslamb/doppel-cli#77]
Right now, the fact that this project only supports Python 3.5 and up is only documented in [trove classifiers](https://pypi.org/pypi?%3Aaction=list_classifiers). This provides documentation but no enforcement.

Should add a version floor explicitly in `setup.py`.

**Comment by lorenafreitas** [comment]
I'm having a go at this one :-)

**Comment by jameslamb** [comment]
Thanks for picking this up @lorenafreitas . I'm going to assign it to you here so it's clear to other contributors that you're working on it.
